[Fusion]
# Achtung: macOS blockiert ggf. direkte Schreibzugriffe auf Fusion.app (Sandboxing / SIP)
FusionUID = a5622f4599acfbd64092660b8146f6dfac84b731
# Hinweis: Der Pfad ~/Library/.../CustomThreads wird vom PlugIn "Custom Threads" ignoriert!
ThreadDataPathTemplate = /Users/apos/Library/Application Support/Autodesk/webdeploy/production/__UID_FUSION_360__/Autodesk Fusion.app/Contents/Libraries/Applications/Fusion/Fusion/Server/Fusion/Configuration